-- 千葉県27自治体 完全データ
-- 生成日時: 2025-12-28 05:04:09
-- 収集自治体数: 27
-- データ収集方法: WebSearch API
-- 検証ステータス: すべてVERIFIED
-- 注記: 千葉県は主に一般的な開発指導要綱が中心

INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '茂原市', '千葉県茂原市', '茂原市宅地開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'https://www.city.mobara.chiba.jp/0000000359.html', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '東金市', '千葉県東金市', '東金市宅地開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '旭市', '千葉県旭市', '旭市開発行為等に関する指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '勝浦市', '千葉県勝浦市', '勝浦市開発行為等指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '我孫子市', '千葉県我孫子市', '我孫子市開発行為に関する条例', '千葉県公式サイト・各市町村公式サイト', 'https://www.city.abiko.chiba.jp/jigyousha/kaihatsu_shinsei/koui/jorei_kijun.html', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '鴨川市', '千葉県鴨川市', '鴨川市開発行為及び大型建築物等建築事業指導要綱', '千葉県公式サイト・各市町村公式サイト', 'https://www.city.kamogawa.lg.jp/soshiki/26/1182.html', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '鎌ケ谷市', '千葉県鎌ケ谷市', '鎌ケ谷市宅地開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'http://www.city.kamagaya.chiba.jp/sesakumidashi/soshiki-annai/toshikensetsu/toshikeikaku/kaihatsu.html', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '君津市', '千葉県君津市', '君津市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '富津市', '千葉県富津市', '富津市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '浦安市', '千葉県浦安市', '浦安市宅地開発等指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '四街道市', '千葉県四街道市', '四街道市宅地開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'https://www.city.yotsukaido.chiba.jp/kurashi/sumai/sumai/kaihatu-koui.html', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '袖ケ浦市', '千葉県袖ケ浦市', '袖ケ浦市宅地開発事業指導要綱', '千葉県公式サイト・各市町村公式サイト', 'https://www.city.sodegaura.lg.jp/soshiki/kaihatsu/kaihatsukyokanogaiyou.html', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '八街市', '千葉県八街市', '八街市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '印西市', '千葉県印西市', '印西市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '白井市', '千葉県白井市', '白井市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '富里市', '千葉県富里市', '富里市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '南房総市', '千葉県南房総市', '南房総市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '匝瑳市', '千葉県匝瑳市', '匝瑳市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '香取市', '千葉県香取市', '香取市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '山武市', '千葉県山武市', '山武市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', 'いすみ市', '千葉県いすみ市', 'いすみ市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '大網白里市', '千葉県大網白里市', '大網白里市開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '酒々井町', '千葉県酒々井町', '酒々井町開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '栄町', '千葉県栄町', '栄町開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '神崎町', '千葉県神崎町', '神崎町開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '多古町', '千葉県多古町', '多古町開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('千葉県', '東庄町', '千葉県東庄町', '東庄町開発指導要綱', '千葉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:09', 1);
