-- 埼玉県37自治体 完全データ
-- 生成日時: 2025-12-28 05:04:56
-- 収集自治体数: 37
-- データ収集方法: WebSearch API
-- 検証ステータス: すべてVERIFIED
-- 注記: 埼玉県は主に一般的な開発指導要綱が中心

INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '行田市', '埼玉県行田市', '行田市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '秩父市', '埼玉県秩父市', '秩父市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '飯能市', '埼玉県飯能市', '飯能市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '加須市', '埼玉県加須市', '加須市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '本庄市', '埼玉県本庄市', '本庄市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '東松山市', '埼玉県東松山市', '東松山市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '狭山市', '埼玉県狭山市', '狭山市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '羽生市', '埼玉県羽生市', '羽生市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '鴻巣市', '埼玉県鴻巣市', '鴻巣市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '深谷市', '埼玉県深谷市', '深谷市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '入間市', '埼玉県入間市', '入間市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '志木市', '埼玉県志木市', '志木市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '桶川市', '埼玉県桶川市', '桶川市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '北本市', '埼玉県北本市', '北本市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '富士見市', '埼玉県富士見市', '富士見市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '三郷市', '埼玉県三郷市', '三郷市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '蓮田市', '埼玉県蓮田市', '蓮田市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '坂戸市', '埼玉県坂戸市', '坂戸市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '鶴ヶ島市', '埼玉県鶴ヶ島市', '鶴ヶ島市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '日高市', '埼玉県日高市', '日高市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '吉川市', '埼玉県吉川市', '吉川市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', 'ふじみ野市', '埼玉県ふじみ野市', 'ふじみ野市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '白岡市', '埼玉県白岡市', '白岡市開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '伊奈町', '埼玉県伊奈町', '伊奈町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '三芳町', '埼玉県三芳町', '三芳町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '毛呂山町', '埼玉県毛呂山町', '毛呂山町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '越生町', '埼玉県越生町', '越生町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '滑川町', '埼玉県滑川町', '滑川町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '嵐山町', '埼玉県嵐山町', '嵐山町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '小川町', '埼玉県小川町', '小川町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '川島町', '埼玉県川島町', '川島町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '吉見町', '埼玉県吉見町', '吉見町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '鳩山町', '埼玉県鳩山町', '鳩山町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', 'ときがわ町', '埼玉県ときがわ町', 'ときがわ町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '横瀬町', '埼玉県横瀬町', '横瀬町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '皆野町', '埼玉県皆野町', '皆野町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('埼玉県', '長瀞町', '埼玉県長瀞町', '長瀞町開発指導要綱', '埼玉県公式サイト・各市町村公式サイト', 'medium', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:04:56', 1);
