-- 東京都17市 完全データ
-- 生成日時: 2025-12-28 05:02:31
-- 収集自治体数: 17
-- データ収集方法: WebSearch API
-- 検証ステータス: すべてVERIFIED

INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '昭島市', '東京都昭島市', '昭島市宅地開発等指導要綱', '昭島市公式サイト', 'https://www.city.akishima.lg.jp/reiki/reiki_honbun/g131RG00001009.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_restrictions, apartment_construction_feasible) VALUES ('東京都', '小平市', '東京都小平市', '小平市開発事業における手続及び基準等に関する条例', '小平市公式サイト', 'https://www.city.kodaira.tokyo.jp/reiki/reiki_honbun/g135RG00001188.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 'ワンルームマンションは計画戸数の100%以上の自転車駐車場が必要', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_restrictions, apartment_construction_feasible) VALUES ('東京都', '日野市', '東京都日野市', '日野市まちづくり指導基準', '日野市公式サイト', 'https://www1.g-reiki.net/hino/reiki_honbun/f900RG00001192.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', '単身者用共同住宅の定義あり。ごみ集積所面積等の規定', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '東村山市', '東京都東村山市', '東村山市宅地開発及び建築物の建築に関する指導要綱', '東村山市公式サイト', 'https://www.city.higashimurayama.tokyo.jp/shisei/machi/takuchi/kaihatu.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_restrictions, apartment_construction_feasible) VALUES ('東京都', '国分寺市', '東京都国分寺市', '国分寺市ワンルーム建築物に関する基準', '国分寺市公式サイト', 'https://www.city.kokubunji.tokyo.jp/area/reiki_int/reiki_honbun/c000RG00001028.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 'ワンルーム建築物は1区分の面積25㎡以上となるよう努める', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_restrictions, apartment_construction_feasible) VALUES ('東京都', '国立市', '東京都国立市', '国立市まちづくり条例', '国立市公式サイト', 'https://www.city.kunitachi.tokyo.jp/machi/keikaku/9355.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', '条例施行規則でワンルーム形式建築物の規定あり', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '福生市', '東京都福生市', '福生市宅地開発等指導要綱', '福生市公式サイト', 'https://www.city.fussa.tokyo.jp/municipal/cityplan/inquiry/1003594.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '狛江市', '東京都狛江市', '狛江市まちづくり条例', '狛江市公式サイト', 'https://www.city.komae.tokyo.jp/index.cfm/46,98424,366,2218,html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '東大和市', '東京都東大和市', '東大和市街づくり条例', '東大和市公式サイト', 'https://www.city.higashiyamato.lg.jp/_res/projects/default_project/_page_/001/011/288/20250326.pdf', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_restrictions, apartment_construction_feasible) VALUES ('東京都', '清瀬市', '東京都清瀬市', '清瀬市住環境の整備に関する条例', '清瀬市公式サイト', 'https://www.city.kiyose.lg.jp/siseijouhou/machizukuri/kaihatu/1004482.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 'ワンルーム形式の建築物についての規定あり', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '東久留米市', '東京都東久留米市', '東久留米市宅地開発等に関する条例', '東久留米市公式サイト', 'https://www.city.higashikurume.lg.jp/shisei/sesaku/toshi/takuchi/1002424.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '武蔵村山市', '東京都武蔵村山市', '武蔵村山市まちづくり条例', '武蔵村山市公式サイト', 'https://www.city.musashimurayama.lg.jp/shisei/toshi/takuchi/1002831.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '多摩市', '東京都多摩市', '多摩市街づくり条例', '多摩市公式サイト', 'https://www.city.tama.lg.jp/_res/projects/default_project/_page_/001/005/016/sidoukijyunngaiyou2.pdf', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '稲城市', '東京都稲城市', '稲城市内の宅地開発事業における建築物の最低敷地面積に関する条例', '稲城市公式サイト', 'https://www1.g-reiki.net/inagi/reiki_honbun/g149RG00000459.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_construction_feasible) VALUES ('東京都', '羽村市', '東京都羽村市', '羽村市宅地開発指導要綱', '羽村市公式サイト', 'https://www.city.hamura.tokyo.jp/0000001403.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_restrictions, apartment_construction_feasible) VALUES ('東京都', 'あきる野市', '東京都あきる野市', 'あきる野市宅地開発等指導要綱', 'あきる野市公式サイト', 'https://www.city.akiruno.tokyo.jp/0000000742.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 'ワンルームを含む集合住宅の規定あり', 1);
INSERT OR REPLACE INTO building_regulations (prefecture, city, normalized_address, local_ordinance, data_source, data_source_url, confidence_level, verification_status, verified_by, verified_at, apartment_restrictions, apartment_construction_feasible) VALUES ('東京都', '西東京市', '東京都西東京市', '西東京市人にやさしいまちづくり条例・西東京市ワンルーム建築物に関する基準', '西東京市公式サイト', 'https://www.city.nishitokyo.lg.jp/siseizyoho/matidukuri/machizukurizyourei.html', 'high', 'VERIFIED', 'AI_Assistant_WebSearch', '2025-12-28 05:02:31', 'ワンルーム建築物は床面積30㎡未満の住戸で構成。駐車・駐輪施設の設置義務', 1);
